# carvision — one command per pipeline stage.
# Everything except `setup` assumes the venv is active.

PY      ?= python
VENV    ?= .venv

# Torch wheel index. The default is the CPU build: this project is designed around
# having no GPU, and the PyPI default would pull a ~2.5 GB CUDA build that does
# nothing here. Override for a GPU box, e.g.
#   make setup TORCH_INDEX=https://download.pytorch.org/whl/cu124
TORCH_INDEX ?= https://download.pytorch.org/whl/cpu
BACKBONE ?= dinov2_vits14
HEAD     ?= linear
SEED     ?= 0

.DEFAULT_GOAL := help

.PHONY: help
help:  ## Show this help.
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

# ----------------------------------------------------------------- setup

.PHONY: setup
setup:  ## Create a venv and install everything (CPU torch by default).
	$(PY) -m venv $(VENV)
	$(VENV)/bin/pip install --upgrade pip
	# Install torch from $(TORCH_INDEX) first. pip then sees the requirement already
	# satisfied and will not reinstall it from PyPI when the package goes in below.
	$(VENV)/bin/pip install torch torchvision --index-url $(TORCH_INDEX)
	$(VENV)/bin/pip install -e ".[dev,export,app]"
	$(VENV)/bin/pre-commit install
	@echo
	@echo "Installed: $$($(VENV)/bin/python -c 'import torch; print(\"torch\", torch.__version__)')"
	@echo "Next: make sync   (install the pinned set from requirements.lock)"
	@echo "  or: make data   (download Stanford Cars and write the splits)"

.PHONY: sync
sync:  ## Install the exact pinned versions from requirements.lock.
	# Same two-step order as `setup`, and for the same reason: take torch from the
	# wheel index that matches this machine first. Doing it in one pass with
	# --extra-index-url lets pip choose either index for torch, which is how a CPU
	# box ends up with a CUDA build.
	$(VENV)/bin/pip install --index-url $(TORCH_INDEX) \
	  $$(grep -E '^(torch|torchvision)==' requirements.lock | tr '\n' ' ')
	# Everything else from PyPI. torch is already satisfied, so it is left alone.
	$(VENV)/bin/pip install --requirement requirements.lock
	$(VENV)/bin/pip install -e . --no-deps

.PHONY: lock
lock:  ## Regenerate requirements.lock from the current environment.
	@printf '%s\n' \
	  '# Generated by `make lock` from a working environment. Do not edit by hand.' \
	  '#' \
	  '# Install with `make sync`, which resolves torch against TORCH_INDEX (the CPU' \
	  '# wheel index by default) and everything else against PyPI.' \
	  '#' \
	  '# torch and torchvision are pinned without a local version suffix (no +cpu or' \
	  '# +cu124) so the same pin works on either index.' \
	  '#' \
	  '# CUDA runtime packages (nvidia-*, triton, cuda-*) are deliberately excluded.' \
	  '# They are dependencies of the CUDA torch build only; pulling them into a CPU' \
	  '# environment costs ~2.5 GB for nothing. Installing torch from a CUDA index' \
	  '# brings them back in as transitive dependencies, which is correct there.' \
	  > requirements.lock
	$(VENV)/bin/pip freeze --exclude-editable \
	  | sed -E 's/^(torch|torchvision|torchaudio)==([^+]+)\+.*/\1==\2/' \
	  | grep -viE '^(nvidia[-_]|triton==|cuda[-_](toolkit|bindings|pathfinder)==)' \
	  | sort -f \
	  >> requirements.lock
	@echo "Wrote requirements.lock ($$(grep -c '==' requirements.lock) pinned packages)"

# ----------------------------------------------------------------- quality

.PHONY: lint
lint:  ## Run ruff (lint + format check).
	ruff check src tests app
	ruff format --check src tests app

.PHONY: format
format:  ## Autoformat and autofix.
	ruff check --fix src tests app
	ruff format src tests app

.PHONY: typecheck
typecheck:  ## Run mypy in strict mode over src/.
	mypy

.PHONY: test
test:  ## Run the test suite (no network, no dataset).
	pytest -m "not slow"

.PHONY: check
check: lint typecheck test  ## Everything CI runs.

# ----------------------------------------------------------------- pipeline

.PHONY: data
data:  ## Download Stanford Cars and write the deterministic splits.
	carvision data download
	carvision data split

.PHONY: cache
cache:  ## Build the frozen-backbone embedding cache for one backbone.
	carvision cache build --backbone $(BACKBONE)

.PHONY: cache-all
cache-all:  ## Build the embedding cache for every backbone (slow, once).
	for b in resnet50 clip_vitb32 dinov2_vits14; do carvision cache build --backbone $$b; done

.PHONY: train
train:  ## Train one head on cached embeddings.
	carvision train backbone=$(BACKBONE) head=$(HEAD) seed=$(SEED)

.PHONY: sweep
sweep:  ## 3 backbones x 2 heads x 5 seeds on cached embeddings.
	carvision sweep

.PHONY: zeroshot
zeroshot:  ## CLIP zero-shot baseline (no training).
	carvision zeroshot

.PHONY: eval
eval:  ## Evaluate the best run: metrics, CIs, calibration.
	carvision eval --run best

.PHONY: figures
figures:  ## Regenerate every figure in docs/figures/.
	carvision figures

.PHONY: report
report:  ## Regenerate docs/RESULTS.md from the evaluated runs.
	carvision report

.PHONY: export
export:  ## Export to ONNX and verify parity with PyTorch.
	carvision export --run best

.PHONY: bench
bench:  ## Benchmark CPU latency, PyTorch vs ONNX Runtime.
	carvision bench

.PHONY: demo
demo:  ## Run the Gradio demo locally.
	cd app && $(PY) app.py

.PHONY: all
all: data cache-all sweep zeroshot eval figures report export bench  ## Full pipeline from scratch.

# ----------------------------------------------------------------- misc

.PHONY: clean
clean:  ## Remove caches and build artifacts (keeps data/ and artifacts/).
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage coverage.xml build dist
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
